Repository esi-neuroscience/syncopy, pull requests merged in 2022-12, with the labels that each got.

#385 384 deprecate toitoilim and foifoilim for selectdata
  CHANGELOG.md
  doc/source/quickstart/quickstart.rst
  syncopy/datatype/base_data.py
  syncopy/datatype/continuous_data.py
  syncopy/datatype/discrete_data.py
  syncopy/datatype/methods/definetrial.py
  syncopy/datatype/methods/selectdata.py
  syncopy/nwanalysis/connectivity_analysis.py
  syncopy/plotting/sp_plotting.py
  syncopy/shared/computational_routine.py
  syncopy/shared/latency.py
  syncopy/tests/helpers.py
  syncopy/tests/test_cfg.py
  syncopy/tests/test_computationalroutine.py
  syncopy/tests/test_connectivity.py
  syncopy/tests/test_continuousdata.py
  syncopy/tests/test_discretedata.py
  syncopy/tests/test_metadata.py
  syncopy/tests/test_plotting.py
  syncopy/tests/test_preproc.py
  syncopy/tests/test_resampledata.py
  syncopy/tests/test_selectdata.py
  syncopy/tests/test_specest.py
  syncopy/tests/test_specest_fooof.py
  syncopy/tests/test_spike_psth.py
Labels: FT compat

#386 memory-improvements-nwb
  syncopy/io/__init__.py
  syncopy/io/load_nwb.py
  syncopy/tests/test_spyio.py
Labels: Performance

#388 367 inter trial coherence itc
  CHANGELOG.md
  syncopy/datatype/__init__.py
  syncopy/datatype/continuous_data.py
  syncopy/datatype/methods/show.py
  syncopy/plotting/sp_plotting.py
  syncopy/shared/input_processors.py
  syncopy/statistics/__init__.py
  syncopy/statistics/summary_stats.py
  syncopy/tests/local_spy.py
  syncopy/tests/test_continuousdata.py
  syncopy/tests/test_selectdata.py
  syncopy/tests/test_statistics.py
Labels: Feature Request
