Repository esi-neuroscience/syncopy, pull requests merged in 2023-03, with the labels that each got.

#450 Poetry install failing on github after poetry 1.4.1 release
  .github/workflows/cov_test_workflow.yml
  README.rst
Labels: Critical Bug, dependencies

#459 CHG: Normalize spectra independent of padding
  CHANGELOG.md
  syncopy/specest/freqanalysis.py
  syncopy/specest/mtmconvol.py
  syncopy/specest/mtmfft.py
  syncopy/tests/test_specest.py
Labels: FT compat

#457 456 diskspace warn
  CHANGELOG.md
  syncopy/__init__.py
  syncopy/datatype/base_data.py
  syncopy/datatype/util.py
  syncopy/tests/test_datatype_util.py
  syncopy/tests/test_statistics.py
Labels: Bug
