Repository esi-neuroscience/syncopy, pull requests merged in 2023-04, with the labels that each got.

#479 478 creating a dummy dataset using snpanalogdata does not create a data set with desired name of the channels
  syncopy/datatype/continuous_data.py
  syncopy/tests/test_continuousdata.py
Labels: Minor Bug

#481 CHG: Handle NaNs in preprocessing
  CHANGELOG.md
  syncopy/preproc/compRoutines.py
  syncopy/preproc/firws.py
  syncopy/preproc/preprocessing.py
  syncopy/tests/test_preproc.py
Labels: Feature Request, FT compat

#482 475 undo poetry version pin
  .github/workflows/cov_test_workflow.yml
  .gitlab-ci.yml
  doc/source/developer/developer_api.rst
  poetry.lock
  pyproject.toml
Labels: Documentation, dependencies

#477 NEW: Standalone synthetic data module
  CHANGELOG.md
  syncopy/__init__.py
  syncopy/shared/kwarg_decorators.py
  syncopy/synthdata/__init__.py
  syncopy/synthdata/analog.py
  syncopy/synthdata/spikes.py
  syncopy/synthdata/utils.py
  syncopy/tests/backend/test_conn.py
  syncopy/tests/backend/test_fooofspy.py
  syncopy/tests/local_spy.py
  syncopy/tests/test_cfg.py
  syncopy/tests/test_connectivity.py
  syncopy/tests/test_decorators.py
  syncopy/tests/test_metadata.py
  syncopy/tests/test_plotting.py
  syncopy/tests/test_preproc.py
  syncopy/tests/test_resampledata.py
  syncopy/tests/test_spike_psth.py
  syncopy/tests/test_statistics.py
  syncopy/tests/test_synthdata.py
  syncopy/tests/test_timelockanalysis.py
  syncopy/tests/test_welch.py
Labels: Design, Tests
